name: 'SelfHostedLocal'  # Pipeline run name

trigger: none  # Disable CI trigger for current repo

resources:
  repositories:
    - repository: TestRepo
      type: github
      name: Ariyakrishna/TestRepo
      endpoint: Ariyakrishna
      ref: refs/heads/main
      trigger:
        branches:
          include:
            - main

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: SelfHostedLocal
    steps:
    - checkout: self
    - checkout: TestRepo  # ✅ Fixed alias
    - script: echo "Triggering build because Ariyakrishna/TestRepo changed"
