name: 'SelfHostedLocal'  # Pipeline run name

trigger: none  # Disable CI trigger for current repo

resources:
  repositories:
    - repository: firstAppRepo
      type: github
      name: Ariyakrishna/first-app
      endpoint: Ariyakrishna
      ref: refs/heads/main
      trigger:
        branches:
          include:
            - main

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: SelfHostedLocal  # ✅ Your custom self-hosted agent pool
    steps:
    - checkout: self
    - checkout: firstAppRepo  # Checkout the external GitHub repo
    - script: echo "Triggering build because Ariyakrishna/first-app changed"
